export const ENDPOINTS = {
    auth: {
        login: "/user/login",
        logout: "/user/logout",
    },
    session: {
        keepalive: "/session/keepalive",
        context: "/session/context",
    },
    company: {
        list: "/master/company",
        save: "/company/save",
        delete: "/company/delete",
        options: "/company/getOption",
    },
    shipping: {
        list: "/master/shipping",
        save: "/shipping/save",
        delete: "/shipping/delete",
    },
    origin: {
        list: "/master/origin",
        save: "/origin/save",
        delete: "/origin/delete",
    },
    lab: {
        list: "/master/lab",
        save: "/lab/post",
        delete: "/lab/delete",
    },
    category: {
        list: "/master/category",
        save: "/category/save",
        delete: "/category/delete",
    },
    common: {
        increment: "/common/getIncrement",
    },
    product: {
        inventory: "/product/inventory",
        inventorySummary: "/product/inventory/summary",
        inventorySuggest: "/product/inventory/suggest",
        detail: "/product/detail",
        save: "/product/save",
        holdDetail: "/product/holdDetail",
        changePrice: "/product/change-price",
        labelA4Print: "/product/label-a4/print",
        labelPrint: "/product/label/print",
        iExport: "/product/i-export",
        export: "/product/export",
        mail: "/product/mail",
        history: "/product/history",
        boxAdd: "/product/box/add-stones",
        parcelAdd: "/product/parcel/add-stones",
        categorizeTree: "/product/categorize/tree",
        categorizeAssign: "/product/categorize/assign",
        categorizeStats: "/product/categorize/stats",
        pairAssign: "/product/pair/assign",
        pairUnpair: "/product/pair/unpair",
        packageAssign: "/product/package/assign",
    },
    inward: {
        checkExist: "/inward/checkExist",
        save: "/inward/save",
    },
    transactionStock: {
        gia: {
            list: "/transaction/gia/list",
            return: "/transaction/gia/return",
            delete: "/transaction/gia",
        },
        inward: {
            list: "/transaction/inward-stock/list",
            return: "/transaction/inward-stock/return",
            memoToPurchase: "/transaction/inward-stock/memo-to-purchase",
            delete: "/transaction/inward-stock",
        },
        purchase: {
            list: "/transaction/purchase-stock/list",
            toggleType: "/transaction/purchase-stock/toggle-type",
        },
        outward: {
            list: "/transaction/outward-stock/list",
            return: "/transaction/outward-stock/return",
            memoToSale: "/transaction/outward-stock/memo-to-sale",
            toExport: "/transaction/outward-stock/to-export",
            delete: "/transaction/outward-stock",
        },
        print: "/transaction/print",
    },
    outward: {
        list: "/outward/list",
        getProducts: "/outward/getProducts",
        getById: "/outward",
        update: "/outward/update",
        delete: "/outward",
        sendTo: "/outward/sendTo",
        hold: "/outward/hold",
    },
    expanse: {
        list: "/expanse/get",
        payment: "/expanse-payment",
        delete: "/expanse-delete",
    },
    advance: {
        list: "/advance/get",
        payment: "/advance-payment",
        delete: "/advance-delete",
    },
    partyWise: {
        list: "/partywisetransaction",
        save: "/partywisetransaction/save",
        delete: "/partywisetransaction/delete",
    },
    accountingTxn: {
        list: "/transaction",
        advanceReport: "/transaction/advance-report",
        books: "/transaction/books",
    },
    balance: {
        list: "/balance/get",
        book: "/my-balance-book",
        delete: "/my-balance-delete",
    },
    currency: {
        list: "/currency-rate/get",
        save: "/currency-rate",
        delete: "/currency-rate-delete",
    },
    report: {
        outstanding: "/report/outstanding",
        outstandingRecords: "/report/outstandingRecords",
        outstandingCharge: "/report/outstanding/charge",
        outstandingInstallment: "/report/outstanding/installment",
        group: "/report/group",
        saleStock: "/report/sale-stock",
        stoneDetail: "/report/stone-detail",
        stoneInfo: "/report/stone-info",
        transferHistory: "/report/transfer-history",
        filterOptions: "/report/filter-options",
        transaction: "/report/transaction",
    },
    dashboard: {
        summary: "/dashboard/summary",
    },
    rapnet: {
        prices: "/rapnet/prices",
        updatePrice: "/rapnet/update-price",
        live: "/rapnet/live",
        history: "/rapnet/history",
        snapshot: "/rapnet/live/snapshot",
    },
    attribute: {
        list: "/master/attribute",
        save: "/attribute/save",
        delete: "/attribute/delete",
        options: "/attribute/getOption",
    },
    accountingGroup: {
        list: "/accounting/group",
        save: "/accounting/group/save",
        delete: "/accounting/group/delete",
    },
    accountingSubgroup: {
        list: "/accounting/subgroup",
        save: "/accounting/subgroup/save",
        delete: "/accounting/subgroup/delete",
    },
    portal: {
        companyYears: "/portal/company-years",
        years: "/portal/years",
        addYear: "/portal/year",
        updateYear: "/portal/year",
        deleteYear: "/portal/year",
    },
    tenantCompany: {
        list: "/admin/tenant-company",
        detail: (id) => `/admin/tenant-company/${id}`,
        save: "/admin/tenant-company/save",
        delete: "/admin/tenant-company/delete",
        options: "/admin/tenant-company/options",
    },
    integration: {
        refreshRapnetStock: "/integration/refresh-rapnet-stock",
        giaLookup: "/integration/gia-lookup",
        websiteSync: "/integration/website-sync",
    },
    legacyApps: "/config/legacy-apps",
    bulk: {
        update: "/bulk-update",
    },
    admin: {
        users: "/getAdminManageUser",
        saveUser: "/admin-manage-user",
        deleteUser: "/manage-user/delete",
        activityLog: "/admin/activity-log",
        activityLogGrouped: "/admin/activity-log/grouped",
        activityLogGroupDetail: "/admin/activity-log/group-detail",
        activityLogExport: "/admin/activity-log/export",
        activityLogDelete: "/admin/activity-log/delete",
        activityLogDeleteAll: "/admin/activity-log/delete-all",
        activityLogTrack: "/admin/activity-log/track",
        activityLogTrackUi: "/admin/activity-log/track-ui",
        activityLogDetail: (id) => `/admin/activity-log/${id}`,
    },
    role: {
        list: "/role-list",
        add: "/role-add",
        update: "/role-update",
        delete: "/role-delete",
        registry: "/permission-registry",
    },
    profile: {
        me: "/api/profile/me",
        update: "/api/profile/update",
        changePassword: "/api/profile/change-password",
    },
    ai: {
        stockAlert: "/ai/stock-alert",
        priceSuggest: "/ai/price-suggest",
        salesReport: "/ai/sales-report",
        customerInsight: "/ai/customer-insight",
        chat: "/ai/chat",
        agentQuery: "/ai/agent/query",
        threads: "/ai/threads",
        threadDetail: (id) => `/ai/threads/${id}`,
        ocrCertificate: "/ai/ocr/certificate",
        barcodeLookup: "/ai/barcode-lookup",
    },
};


export const QUERY_KEYS = {
    companies: "companies",
    shipping: "shipping",
    origins: "origins",
    labs: "labs",
    categories: "categories",
    users: "users",
};
