// Initial state — field names match dai-product / dai-product_value columns
export const initialFormData = {
  id: undefined,
  mfg_code: "",
  sku: "",
  lab: "GIA",
  polish_pcs: 1,
  polish_carat: null,
  main_color: "",
  cost: null,
  price: null,
  amount: 0,
  location: "",
  remark: "",
  main_group: "",
  sub_group: "",
  in_house_clarity: "",
  argyle_color: "",
  mining: "",
  origin: "",
  report_no: "",
  shape: "",
  clarity: "",
  size: "",
  f_intensity: "",
  cut: "",
  polish: "",
  symmentry: "",
  table_pc: null,
  depth_pc: null,
  mesurment: "",
  gridle: "",
  intensity: "",
  overtone: "",
  color: "",
  package: "",
  group_type: "single",
  category: undefined,
  is_uploadsite: false,
  is_uploadrapnet: false,
  hide: false,
};

export const stoneUploadfields = [
  { name: "mfg_code", label: "Mfg Code", type: "text", span: 6 },
  { name: "sku", label: "SKU / Stone ID", type: "text", span: 6, required: true, disabled: true },
  { name: "lab", label: "Lab", type: "select", span: 6, options: [
    { label: "GIA", value: "GIA" },
    { label: "IGI", value: "IGI" },
    { label: "HRD", value: "HRD" },
  ] },
  { name: "polish_pcs", label: "Pcs", type: "number", span: 6 },
  { name: "polish_carat", label: "Carat", type: "number", span: 6, disabled: true },
  { name: "main_color", label: "Full Color", type: "text", span: 12 },
  { name: "cost", label: "Cost Price", type: "number", span: 6 },
  { name: "price", label: "Selling Price", type: "number", span: 6, disabled: true },
  { name: "amount", label: "Amount", type: "number", span: 6, disabled: true },
  { name: "location", label: "Location", type: "text", span: 6 },
  { name: "remark", label: "Remark", type: "text", span: 12 },
];

export const stoneUploadfieldsBottom = [
  { name: "main_group", label: "Main", type: "text", span: 6 },
  { name: "sub_group", label: "Sub", type: "text", span: 6 },
  { name: "in_house_clarity", label: "In House Clarity", type: "text", span: 6 },
  { name: "argyle_color", label: "Argyle Color", type: "text", span: 6 },
  { name: "mining", label: "Mining", type: "text", span: 6 },
  { name: "origin", label: "Origin", type: "text", span: 6 },
  { name: "report_no", label: "Certificate No", type: "text", span: 6 },
  { name: "shape", label: "Shape", type: "text", span: 6 },
  { name: "size", label: "Size", type: "text", span: 6 },
  { name: "f_intensity", label: "Fluorescence", type: "text", span: 6 },
  { name: "cut", label: "Cut", type: "text", span: 6 },
  { name: "polish", label: "Polish", type: "text", span: 6 },
  { name: "symmentry", label: "Symm", type: "text", span: 6 },
  { name: "table_pc", label: "Table %", type: "number", span: 6 },
  { name: "depth_pc", label: "Depth %", type: "number", span: 6 },
  { name: "mesurment", label: "Measurement", type: "text", span: 6 },
  { name: "gridle", label: "Girdle", type: "text", span: 6 },
  { name: "intensity", label: "Intensity", type: "text", span: 6 },
  { name: "overtone", label: "Overtone", type: "text", span: 6 },
  { name: "color", label: "Color", type: "text", span: 6 },
  { name: "package", label: "Package", type: "text", span: 6 },
];

export const stoneTypeOptions = [
  { label: "Single", value: "single" },
  { label: "Box", value: "box" },
  { label: "Parcel", value: "parcel" },
];
