export const tenantCompanyFields = [
  { type: "input", label: "Company Name", name: "name", span: 24, required: true },
  { type: "input", label: "Type", name: "type", span: 12 },
  { type: "input", label: "Phone Number", name: "number", span: 12, required: true },
  { type: "textarea", label: "Name of Partner", name: "partner", span: 24 },
  { type: "textarea", label: "Address", name: "address", span: 24, required: true },
  { type: "input", label: "City", name: "city", span: 8 },
  { type: "input", label: "State", name: "state", span: 8 },
  { type: "input", label: "Pincode", name: "pincode", span: 8 },
  { type: "input", label: "Country", name: "country", span: 12 },
  { type: "input", label: "E-Mail", name: "email", span: 12 },
  { type: "input", label: "Website", name: "website", span: 12 },
  { type: "input", label: "PAN No.", name: "panno", span: 12 },
  { type: "input", label: "TIN No.", name: "tinno", span: 12 },
  { type: "input", label: "IEC No.", name: "iecno", span: 12 },
  { type: "input", label: "VAT TIN No.", name: "vatno", span: 12 },
  { type: "date", label: "VAT W.E.F.", name: "vwef", span: 12 },
  { type: "input", label: "CST TIN No.", name: "cstno", span: 12 },
  { type: "date", label: "CST W.E.F.", name: "cwef", span: 12 },
  { type: "input", label: "Period", name: "period", span: 12 },
  { type: "date", label: "Book Start Date", name: "startdate", span: 12 },
  { type: "date", label: "Book End Date", name: "enddate", span: 12 },
  { type: "input", label: "RapNet ID", name: "rapnet_id", span: 12 },
  { type: "input", label: "RapNet Password", name: "rapnet_password", span: 12 },
];
